### ISSUE TITLE
Input fields

### ISSUE THREAD

**Issue by maxim3007** [Andereoo/TkinterWeb#13]
Hi again!
When opening pypi.org with htmlframe main search field is white and font color is also white.
Is it possible to change font color if input field is white?

**Comment by Andereoo** [comment]
Hello!

Yes, I can change the font color when both the background and the foreground are the same color. 

I'm not sure I will, though. Try creating an input field with a white foreground and a white background in any standards-compliant browser. The text color will not be changed, since there are a few (extremely) rare cases where one might want both to be the same color. I'd rather mimic that more standard behavior and not change any text coloring for inputs.

**Comment by maxim3007** [comment]
Hi,
Oh yes, I think there are really very rare cases where they have same colors and I think I can solve the issue by using beautifulsoup!
