### ISSUE TITLE
Multiple <br> tags not working together.

### ISSUE THREAD

**Issue by Godkayaki** [Andereoo/TkinterWeb#17]
As the title says, multiple <br> tags aren't recognized individually but just as one of them. Im working with a mail template system and I'm using tkinterweb to make a little previsualization of that mail template;
![06](https://user-images.githubusercontent.com/48527821/124722066-f864fe00-df09-11eb-88b4-4c16e667460a.png)
Maybe I'm doing something wrong but the html code works perfectly on it's own.

**Comment by Andereoo** [comment]
Hi!

Thank you for letting me know about this. You aren't doing anything wrong. 

I can confirm this bug on my end, but it seems to be a Tkhtml bug, so unfortunately fixing it is outside of my scope. That being said, their are a couple of things you could do to work around the issue. One thing you could do is replace `<br/><br/>` with `<p></p>`. A `<p>` tag inserts more-or-less the equivalent of two `<br>` tags. You could also insert a space between the two `<br>` tags. `<br/>&nbsp<br/>` also works as expected, inserting two new lines. The last thing you could do is use margins. It is generally better to use margins or padding to insert spaces, rather than `<br>` tags. Just remember to keep in mind that many email clients require styling information to be inline. 

Hopefully this helps!

**Comment by Godkayaki** [comment]
Oh okay, I didnt thought of tkhtml being the problem, I'll try those and see what works better, thank you!
