### ISSUE TITLE
The  website window is not opening 

### ISSUE THREAD

**Issue by swagat123** [Andereoo/TkinterWeb#2]
Hi ,

I am using python 3.8 . the below code i am using , the site is not loading

```
from tkinter import * 
from tkinterweb import HtmlFrame 

root = Tk() 
frame = HtmlFrame(root) 
frame.load_website("https://www.dummies.com/web-design-development/site-development/a-sample-web-page-in-html/") 
frame.pack(fill="both", expand=True) 
root.mainloop()
```
I got message like 

```
UserNotification: Fetching Tkhtml3 for 64-bit Windows with Python 3.8.7.   
Tkhtml found in C:\Users\User0\python\Python38\Lib\site-packages\tkinterweb\tkhtml\Windows\64-bit.
```

after  that the script execution stopped and no window is opening. is there any thing wrong that i am doing.

Thanks 
Swagat

**Comment by thegame4craft** [comment]
i have exact the same error and the same python version.

**Comment by amalthomas-exe** [comment]
Same problem this side also (python3.7)..

**Comment by amalthomas-exe** [comment]
> Thank you for letting me know. I am working through this issue but it may take a while. In the meantime you _could_ install and use 32-bit Python instead. It is not ideal, but it does work perfectly fine.

@Andereoo thanks for the reply.

However, I'm using tensorflow for my projects which require  python 3.7 64bit . So I think I'll rather wait for the fix.

**Comment by amalthomas-exe** [comment]
Issue not resolved even after new update

`UserNotification: Fetching Tkhtml3 for 64-bit Windows with Python 3.7.9.
Tkhtml3 found in C:\Users\thoma\AppData\Local\Programs\Python\Python37\lib\site-packages\tkinterweb\tkhtml\Windows\64-bit.

UserNotification: Connecting to tkhtml.tcl.tk.`

After this , the script execution ends abruptly.

**Comment by Andereoo** [comment]
I have not resolved this issue yet. It is a problem with the `parse` command in the underlying tkhtml3 code, not with the Python code in this project. I will keep looking for a workaround.

**Comment by amalthomas-exe** [comment]
@Andereoo  Inform us when the issue is resolved..

**Comment by Andereoo** [comment]
@amalthomas-exe I certainly will!

**Comment by migf1** [comment]
I just wanted to add my voice to this issue, along with a couple of screenshots in case they help:
1. https://prnt.sc/11x6i54
2. https://prnt.sc/11x6p7u

Btw, thank you for this project! It sounds great, so I hope you can resolve the problem soon.

**Comment by Abstract-Programming** [comment]
Using 32-bit python 3.9.2 did not work for me.
Got the same message as i did in my 64 bit pipenv:

`UserNotification: Fetching Tkhtml3 for 64-bit Windows with Python 3.9.2. `
`UserNotification: Connecting to ###.###.`

**Comment by Andereoo** [comment]
Hello @Abstract-Programming,
I just installed 32-bit python 3.9.2 but can't seem to reproduce your issue. Make sure that you are using 32-bit Python - not 64-bit Python. Looking at your message, you seem to be using 64-bit Python. Perhaps you installed the wrong version? you may also want to check that you installed and are using Tkinterweb properly. If you still encounter this issue, please let me know and include your code, OS .

**Comment by THEGOLDENPRO** [comment]
Yep, I'm having the same exact issue on python 3.7.9 64 bit. I used the module the same exact way as @swagat123 did in his comment but thanks @Andereoo for paying attention to this issue and @swagat123 for posting the issue I would have thought there was something wrong with my app.
![image](https://user-images.githubusercontent.com/66202304/116783251-ab862680-aa85-11eb-8980-0ec2b69c896f.png)

**Comment by THEGOLDENPRO** [comment]
> Yep, I'm having the same exact issue on python 3.7.9 64 bit. I used the module the same exact way as @swagat123 did in his comment but thanks @Andereoo for paying attention to this issue and @swagat123 for posting the issue I would have thought there was something wrong with my app.
> ![image](https://user-images.githubusercontent.com/66202304/116783251-ab862680-aa85-11eb-8980-0ec2b69c896f.png)

Also, even phrasing HTML doesn't work for me.

**Comment by Andereoo** [comment]
I see. Here's the deal.

This project includes a small Python layer, some TCL code to allow data to transfer between C and Tk (which powers Tkinter), and a bunch of C code that powers the whole thing. 

There are many cases in the C code base where a `0` is passed to a function. This works fine in most operating systems, but not in 64-bit Windows. Normally, that 0 would represent 32 or 64-bits of 0s (depending on the OS). From what I have been able to gather, there is a 64-bit Microsoft C Compiler bug that causes the first 32 bits to be written as 0, and the last 32 bits to be written as some other random objects from the computer's memory. The code expects either a 0 or something else - so when it gets part 0 and part other random objects, it crashes. Other C Compilers don't have this bug, which is who you will likely not see this issue in other operating systems. At the moment, I am working on tweaking a few of these instances to workaround this Microsoft C Compiler bug, but it is taking a while.

When you first load TkinterWeb, it doesn't crash because at that point, you have pretty much only been running TCL and Python code. When you try to parse something, the C code - which takes the HTML/CSS and turns it into something you can actually see in your app - starts firing, but the Microsoft C Compiler bug I mentioned earlier causes the C code to crash. Since at that point the TCL code is relying on the C code, and the Python code is running on the TCL code, when C crashes, the whole app dies.

For now, you can use 32-bit Python (which is able to use 32-bit C, avoiding the Microsoft 64-bit C Compiler bug mentioned earlier), or wait while I keep looking for a workaround.

**Comment by migf1** [comment]
@Andereoo

that's quite interesting (and weird)!

Is the C code written by you? If not, do you have access to its source-code? 
If so, maybe you can try compiling it with a different compiler. Like mingw-w64 for example, or Pelles-C.

You may also try adding preprocessor [macro checks specifically for Windows](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/64-bit-compiler) at compile time, like for example:
```
#if _WIN64
    #define MYZERO ((uint64_t)0)    // or int64_t for signed 0
#elif _WIN32
    #define MYZERO ((uint32_t)0)    // or int32_t for signed 0
#else
    #define MYZERO 0
```
and then pass MYZERO to those function you mentioned.

**Comment by Andereoo** [comment]
Yes, it is wierd.

I have been using mingw-x64 to compile the C code as well, but it seems to be plagued with the same issue. My guess is that it depends on some Windows packages that have the issue I mentioned earlier, or that there is some Microsoft C runtime package that is causing issues; not only Microsoft's compiler. Mingw's gcc itself might have the same issue, but that doesn't quite make sense, since I can use gcc on 64-bit linux to compile the project without any issues.

Regarding the C code, I didn't write it myself. You can download it from http://tkhtml.tcl.tk/tkhtml3-alpha-16.tar.gz. Everything, including compilation instructions and a proof-of-concept webbrowser, is inside the `htmlwidget` folder. The source code that this project runs on should be in the `src` directory.

 Thank you very much for that tip - C is not exactly my strong-point. I'll give it a try and see if I can get it to work!

**Comment by THEGOLDENPRO** [comment]
> I see. Here's the deal.
> 
> This project includes a small Python layer, some TCL code to allow data to transfer between C and Tk (which powers Tkinter), and a bunch of C code that powers the whole thing. 
> 
> There are many cases in the C code base where a `0` is passed to a function. This works fine in most operating systems, but not in 64-bit Windows. Normally, that 0 would represent 32 or 64-bits of 0s (depending on the OS). From what I have been able to gather, there is a 64-bit Microsoft C Compiler bug that causes the first 32 bits to be written as 0, and the last 32 bits to be written as some other random objects from the computer's memory. The code expects either a 0 or something else - so when it gets part 0 and part other random objects, it crashes. Other C Compilers don't have this bug, which is who you will likely not see this issue in other operating systems. At the moment, I am working on tweaking a few of these instances to workaround this Microsoft C Compiler bug, but it is taking a while.
> 
> When you first load TkinterWeb, it doesn't crash because at that point, you have pretty much only been running TCL and Python code. When you try to parse something, the C code - which takes the HTML/CSS and turns it into something you can actually see in your app - starts firing, but the Microsoft C Compiler bug I mentioned earlier causes the C code to crash. Since at that point the TCL code is relying on the C code, and the Python code is running on the TCL code, when C crashes, the whole app dies.
> 
> For now, you can use 32-bit Python (which is able to use 32-bit C, avoiding the Microsoft 64-bit C Compiler bug mentioned earlier), or wait while I keep looking for a workaround.

I see, well I don't know much about C but thank you for the explanation.

**Comment by Giessen** [comment]
is the problem solved?

**Comment by amalthomas-exe** [comment]
Thanks man!

**Comment by THEGOLDENPRO** [comment]
Thank you very much! It seems to be working correctly. 👍
