### ISSUE TITLE
“ModuleNotFoundError: No module named 'bindings'” on compiling with py2app

### ISSUE THREAD

**Issue by Godkayaki** [Andereoo/TkinterWeb#21]
I've been compiling some apps with MacOS using Py2app, so far so good, but i've been having this error when compiling applications that contains the tkinterweb module, I'm not really sure what is causing this.

Error on executing the application:
`Traceback (most recent call last):
  File "MyApp.py", line 40, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "tkinterweb\__init__.py", line 30, in <module>
ModuleNotFoundError: No module named 'bindings'
[4712] Failed to execute script MyApp`

Thanks in advance!

**Comment by Andereoo** [comment]
Hi!

Thanks for letting me know about this. This seems to be an issue similar to https://github.com/Andereoo/TkinterWeb/issues/14. This occurs because TkinterWeb contains a number of files, but some python-to-app programs don't include all the files. In this case, the file `__init__.py` from the `tkinterweb` folder is being bundled, but the other files (such as `bindings.py` aren't). I'm not familiar with Py2app, but there are a couple of things you could do that should work.

1. It looks like you can force Py2app to include packages. You could try something along the lines of adding `"includes": ["tkinterweb"];` to the `OPTIONS` variable in your `setup.py` file (source: [StackOverflow](https://www.stackoverflow.com/questions/62118353/how-does-py2app-add-custom-modules)). This should work like the `--hidden-import=tkinterweb` command line argument for pyinstaller.
2. Another thing you could try if the above fails is locate the location of the output app and find the location of tkinterweb (`import tkinterweb, os; print(os.path.dirname(tkinterweb.__file__))`). Simply copy the entire `tkinterweb` folder to the same directory as your app. I don't exactly reccomend this, though.

Let me know if the above works!

**Comment by Godkayaki** [comment]
I've tried what you told me but it didn't work, but i've been reading the post about adding libraries (which I was already doing with some other libraries that I also had problems with if i didn't specify them into the setup file) and tried adding `tkinterweb` as a **package** and not add it into the **'includes'** option;

```python3
#vars to setup
APP = ['main.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': ICONFILE_PATH,
    'includes': libs,
    'packages': ['tkinterweb']
}
```

This is pure speculation but i think adding the `tkinterweb` on the includes is just doing the same as the compiler does by itself, while adding it onto the packages list works more like the `--collect-all` option from **pyinstaller**, but as I said I'm not really sure.

Thanks for the help and the quick answer!

**Comment by Andereoo** [comment]
No problem! Sorry I couldn't be more helpful, but I'm glad you have sorted out this problem!
