### ISSUE TITLE
Cannot load file created with pyvis properly

### ISSUE THREAD

**Issue by asimard1** [Andereoo/TkinterWeb#30]
![image](https://user-images.githubusercontent.com/58919185/151633309-b1e8e026-aa52-4c0b-b32c-e422e82af0c7.png)

This is what I'm getting, but the window I should be getting is this:

![image](https://user-images.githubusercontent.com/58919185/151633409-ae32989e-e2b3-4fa1-bf7b-67c3cff2fba8.png)

Here is the file I'm trying to load, created using the pyvis library.

[graphFile.txt](https://github.com/Andereoo/TkinterWeb/files/7962358/graphFile.txt)

Is there any way to make this file work?

**Comment by Andereoo** [comment]
Hi! 

Your file is loading fine, but the file uses Javascript.
Unfortunately, TkinterWeb doesn't have much support for Javascript, which explains why your file isn't working right. 
Theoretically, I probably add support for `<canvas>` and Javascript, but I really don't have enough time for that. Hopefully there is some other way you could make this work. 

If you don't need the graph to be interactive, you might be able to open it with something like Selenium, save it as an image, and load the image in Tkinter. Otherwise, I'm not too sure there's an easy way to embed the graph. Maybe try a different GUI toolkit, or if you can, open the file in your webbrowser instead (`import webbrowser; webbrowser.open('path/to/your/file.html')`).

Sorry I couldn't be more helpful.

**Comment by asimard1** [comment]
Thank you anyway!
