### ISSUE TITLE
[Feature request] Rigth click on link

### ISSUE THREAD

**Issue by ShuffleWire** [Andereoo/TkinterWeb#39]
**The feature**
To be able to right click on hypertext link, and trigger a different action.

**Use case**
Be able to emulate the behavior "open in a new tab" or display a drop down menu, or whatever else.

**Possible implementation**
Add a method HtmlFrame.on_link_right_click(callback), triggered on right click.
AFAIK, binding stuff on `ButtonRelease-3` should do it.

**Also**
Same idea with wheel click, and by extension all the button that Tkinter is aware of ?

**Also again**
To display a drop down menu "Browers-like style", I found this article that seems to be a good way to go. I don't what you want to do with it, but I'm leaving it here :) 
https://www.geeksforgeeks.org/right-click-menu-using-tkinter/

**Comment by Andereoo** [comment]
Hi!

Thanks for your suggestion. I think that hard-coding every binding would be redundant. It would be better to leave that to whoever is using TkinterWeb. This would also give you much more control over what happens on right-clicks. TkinterWeb is supposed to be very easy to build on and extend, but it isn't supposed to be a full web browser on its own. This means that extra features such as popups or tabs are not within the scope of this project, but should be easy to add yourself.

That being said, I just added the function `resolve_url` to help make it easier to get the hyperlink. You will need to upgrade TkinterWeb in order to use this function.

You can use `url = frame.get_currently_hovered_node_attribute("href")` to get the `href` of the hyperlink. Then run `url = frame.resolve_url(url)` to get the full url of the hyperlink (since many links only have partial or relative urls). Here's an example from the HtmlFrame docs that can get you started:

```
import tkinter as tk
from tkinterweb import HtmlFrame

root = tk.Tk()

myhtmlframe = HtmlFrame(root)
myhtmlframe.pack(fill="both", expand=True)
myhtmlframe.load_html("""<a class="center-red" href="http://tkhtml.tcl.tk">TEST</a>""")

def copy_url(url):
    root.clipboard_clear()
    root.clipboard_append(url)

def on_right_click(event):
    if myhtmlframe.get_currently_hovered_node_tag() == "a": #if the mouse is over a link
        link = myhtmlframe.get_currently_hovered_node_attribute("href") #get the link's url
        url = myhtmlframe.resolve_url(link) #get a full url from the link
        menu = tk.Menu(root, tearoff=0) #create the menu
        menu.add_command(label="Open %s" % url, command=lambda url=url: myhtmlframe.load_url(url))
        menu.add_command(label="Copy %s" % url, command=lambda url=url: copy_url(url))
        menu.tk_popup(event.x_root, event.y_root, 0) #show the menu


myhtmlframe.bind("<Button-3>", on_right_click)

root.mainloop()
```

Here, right-clicking a link will open a popup with two buttons. Clicking one loads the website, and clicking the other copies the link.

Hope this helps!

**Comment by ShuffleWire** [comment]
Ok, I was not asking for so much xD But thank anyway for the work.
The thing is that I'm not using tkinterweb to load web page, but html code that is generated on the fly by my own app.
So, the html code code be somewhat "tuned" to match tkinterweb capabilites.
I just want to avoid manually building an HMI (with Qt or else) and simply render HTML is very convient !

That being said, `myhtmlframe.bind("<Button-3>", on_right_click)` is what I need xD After that I will be able to trigger whatever action I like, but I'm in charge at this point :)
