### ISSUE TITLE
tkinterweb.HtmlFrame's on_form_submit function is not getting called on all submit buttons in different forms of HTML

### ISSUE THREAD

**Issue by lalitdagre** [Andereoo/TkinterWeb#48]
HtmlFrame.on_form_submit is not functioning properly. In the example the HTML consist of two form having individual submit button. First form submit button's on_form_submit is triggering but another submit button's on_form_submit is not triggering. 

```
from tkinterweb import HtmlFrame #import the HtmlFrame widget
try:
  import tkinter as tk #python3
except ImportError:
  import Tkinter as tk #python2
root = tk.Tk() #create the Tkinter window


def on_form_submit(url, data, method):
    try:
        print(url, data, method)
    except Exception as error:
        print (error)

user_html = """
                    <html>
                        <table>
                            <tr>
                                <form action="value.test" name="one" id="one" method="GET">
                                    <td>Site1<a href="test.html"></a><input type="hidden" name="myhidden1" value="site1"></td>
                                    <td><input type="submit" value="Open in Browser"></td>
                                </form>
                            </tr>
                            <tr>
                                <form action="value.test" name="two" id="two" method="GET">
                                    <td>site2<a href="test1.html"></a><input type="hidden" name="myhidden2" value="site2"></td>
                                    <td><input type="submit" value="Open in Browser"></td>
                                </form>
                            </tr>


                        </table>
                        
                        </ol>    
                        </div>                   
                    </html>
                """


### The important part: create the html widget and attach it to the window
myhtmlframe = HtmlFrame(root) #create HTML browser
myhtmlframe.load_html(user_html) #Load some HTML code
myhtmlframe.pack(fill="both", expand=True) #attach the HtmlFrame widget to the parent window
myhtmlframe.on_form_submit(on_form_submit)

root.mainloop()
```

**Comment by Viswas-Programs** [comment]
I think renaming the function will do the trick, because the function names are clashing between `myhtmlframe.on_form_submit` and `yourfile.on_form_submit `method.
I'm not sure though

**Comment by nickzoic** [comment]
This is going to sound ridiculous, but if you remove the <table> and <tr> elements from your example code it works as expected.   Interestingly if I add another tr and another form, the first two work and the last one doesn't!

It seems like when the table is there, TkInterWeb.on_form is getting called with the wrong widgets, and thus failing to set up the last form correctly?  I don't really understand how the parsing/widget replacement logic is working though.

**Comment by Andereoo** [comment]
Hi! I noticed the same thing earlier. It _does_ seem ridiculous, but it looks like the underlying Tkhtml code is not able to detect items inside tables while loading. 

To answer your question @nickzoic  Every time a new form is detected, the document is scanned for buttons or inputs, which are added to the form if they have not already been detected. Let's say that there are only two forms. Normally, as each first form is parsed, the items inside are detected and added to a table that matches form elements with their corresponding form. This table is used to figure out which information to include when a form is submitted. With tables, though, no items are detected inside the current form. This means that nothing is added to the table for the first form, and when the second form is loaded, nothing is found inside the second form, but the items that should have been detected in the first form _are_ found and are then added to the second form. Weird.

I've updated the source code to scan each individual form for content rather than the document as a whole. This fixes the weird behaviour with tables getting mixed up, and an input that is not inside a form will no longer be assigned to the first form present, but this also means that now forms inside tables do absolutely nothing. I'm not sure which is better. Let me know what you think.

As this seems to be a strange bug in the underlying html engine, it doesn't look like there is anything I can do on my end. The best I can suggest is to try not to use tables for forms (i.e. try using a `<div>` instead).

**Comment by nickzoic** [comment]
Isn't that weird!  Yeah, I worked out your code for detecting form fields, but haven't looked under the hood of Tkhtml and I'm a little bit afraid to :-)

I'm guessing it builds the table widget tree separately and then adds it to the document widget tree when it finishes laying it out, so the embedded form can't be found until then, or something like that anyway. As you point out, the form is there in the tree when the *next* form loads.  I wonder if it'd work better to wait for the whole document to finish loading before doing the form field scan?

PS: I think setup.py is on PyPI but missing from the github repo?

**Comment by Andereoo** [comment]
Thanks for the suggestion @nickzoic. I added some code that scans tables after they have loaded, which seems be a good workaround for this issue. @lalitdagre, upgrade TkinterWeb, and let me know if the issue still persists!
