### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by maxim3007** [Andereoo/TkinterWeb#7]
Hello!
I have found a mention of iframe in TkinterWeb's DEFAULT_STYLE and I have an idea how to render iframe.
Maybe you can replace `<iframe src="http://google.com" style="xxx"></iframe>` with `<div widgetid="small_htmlframe_in_main_htmlframe" style="xxx"></div>`.
small_htmlframe_in_main_htmlframe will load a website that is in `src` attribute of iframe.
I hope it was useful.

**Comment by Andereoo** [comment]
Hi!

That's a great idea. I can use the commands that are invoked when an element with a `widgetid` attribute is encountered to implement iframes, similarily too the way certain form elements are shown. I can also use that to implement `<object>` elements (which means that TkinterWeb will be able to pass the [Acid2 test](https://en.wikipedia.org/wiki/Acid2)). Thank you very much for that idea!

The only problem would be avoiding circular imports (because HtmlFrame imports TkinterWeb, and to implement iframes TkinterWeb should import HtmlFrame), but I will figure it out. 

Again, thank you very much for the idea, and I'll let you know when I get it working.

Feel free to let me know if you have any other ideas!

**Comment by maxim3007** [comment]
I have found that iframe has `srcdoc` attribute.
`<iframe srcdoc="<html><body><p>Example</p></body></html>"></iframe>`
So in this case htmlframe must call `load_html `

**Comment by Andereoo** [comment]
I've finished adding basic support for `<object>` and `<iframe>` elements.
At the moment, iframes with an `src` attribute will display the given website in the document, unless the `srcdoc` attribute is supplied, which will cause the iframe to display the given HTML code. 

Consider reinstalling TkinterWeb.
As always, if you have any other suggestions or notice any bugs, feel free to let me know!

Thanks again for the suggestion.
