### ISSUE TITLE
Javascript support

### ISSUE THREAD

**Issue by maxim3007** [Andereoo/TkinterWeb#8]
Hello again!
I know that Hv3 browser is using [`SEE`](https://www.adaptive-enterprises.com.au/~d/software/see/) library for JS rendering .
Maybe you can connect one of JS libs to TkinterWeb using `ctypes`.
I know some libs like `SpiderMonkey`, `KJS`, `WEBKIT`

**Comment by Andereoo** [comment]
Hi!

I'm not sure if I'll actually get around to doing this. 

Hv3's JavaScript support is very flaky, and is quite limited when it comes to interacting with the document. I think that even if I did manage to connect a JavaScript interpreter to this project, it wouldn't be particularly useful, because as far as I can tell, Tkhtml is somewhat limited when it comes to replacing HTML and modifying elements.

Nonetheless, this is a good idea that would be nice to see in this project; I'll look into this.

**Comment by maxim3007** [comment]
Hi!
I've found GitHub repo of `SEE` [here](https://github.com/yujiabe/SEE/).
maybe it will be useful.

**Comment by Andereoo** [comment]
Hi,
For now I will close this as `wontfix`. Due to Tkhtml's limitations, Javascript support will likely never be very useful, and with the little time I have I doubt that it will ever become stable enough. Maybe I'll play around with some of these ideas later, but for not I'm just going to leave TkinterWeb as it is.

**Comment by pythoniaweb** [comment]
js support need to be added!

**Comment by jmerlan** [comment]
I agree, Javascript support would open up so many use-cases for this widget. My idea was to display a Plotly graph in a Tkinter application.

However, I definitely understand that these open source projects are rarely top priority. Thanks for your hard work so far.

**Comment by Andereoo** [comment]
Hi @jmerlan @pythoniaweb @maxim3007 @jofemodo @TsaiTung-Chen @damies13 I know this stream is 4 years old now but I thought I'd offer some updates in case anyone is still using this project.

 Javascript is still not supported 😔 but it is possible to register a handler for `<script>` elements (in case you wanted to write your own markup and interpreter, attach a JS interpreter, or simply put Python code in the block and `eval()` it). There is now also a framework that allows you to [manipulate the DOM](https://tkinterweb.readthedocs.io/en/latest/dom.html) after it's loaded and might be useful for some people. FYI 😊

Still no Plotly graphs, but maybe some day.
