### ISSUE TITLE
Local Images

### ISSUE THREAD

**Issue by JuanJoZP** [Andereoo/TkinterWeb#9]
HtmlLabel doesn't work with local images, it renders and sets the size but its white. I've checked the image path and that the image isn't empty.

```
images = HtmlLabel(
        root, text="<img src='/stickers/a.jpeg' width='50' height='50'/>"
    ).grid(row=3, column=0, columnspan=2)
```
![imagen](https://user-images.githubusercontent.com/63169687/120879392-991d7200-c588-11eb-9657-580824b2c577.png)

**Comment by Andereoo** [comment]
Hi Juan,

HtmlLabel does support local images, but it seems that it is having trouble _finding_ the images.

Here's what is going on. If no base url is specified, TkinterWeb will automatically generate one. In your version of TkinterWeb, the base url will be automatically set to HtmlLabel's directory. This means that if HtmlLabel is in `C://path/to/tkinterweb/`, and you set the image to `stickers/a.jpeg`,  TkinterWeb will think that the image is in `C://path/to/tkinterweb/stickers/a.jpeg`, which is obviously incorrect.  If TkinterWeb cannot find an image, by default it will simply display a blank image in place of the original. That is why you are seeing a blank image with the correct dimentions.

There are three things you can do:
1. Use an absolute url (eg. `<img src="file://path/to/stickers/a.jpeg"></img>`). This is not exactly recommended.

2. Don't pass any HTML to HtmlLabel. Use `label.load_html(text, current_path)`, where `current_path` is the path to your file. This can be generated using something along the lines of `import os; current_path=os.path.abspath(os.path.dirname(__file__))`. You should do this if you are planning to compile your script as an application or run it from different locations.

3. This is probably the best thing to do in your case. I've realized that setting the default base url to TkinterWeb's directory is not particularly helpful, so I have changed it to the current working directory. If you upgrade your TkinterWeb installation, you should be able to load your images without any issues. 

By the way, if you are using Linux, `/stickers/a.jpeg` is technically a valid file path, so the image will literally be fetched from `file:///stickers/a.jpeg`. To avoid this, you might want to set the image's src to `stickers/a.jpeg` (note that the first `/` is missing).

You can always use `HtmlLabel(root, text="<img src='/stickers/a.jpeg' width='50' height='50'/>", messages_enabled=True)` to get debugging information, such as the location of the images it is trying to fetch (which you can compare to your actual files to see what is going wrong), and error messages. If you are still having issues, copy the messages displayed and paste them as a comment so that I can see if there is a bug somewhere that needs to be addressed.

Good luck!

**Comment by Andereoo** [comment]
@JuanJoZP Have I answered your question, or is something still not working?

**Comment by JuanJoZP** [comment]
Hello, you have answered my question, now it is working. Thank you very much

**Comment by Andereoo** [comment]
I'm happy to hear!

I also forgot to mention that you could also use data URLs to show images without having them saved to your hard drive. Take a look at https://css-tricks.com/data-uris/ if you're curious!
